### ISSUE TITLE
Error in prepare_train_data.py when processing in parallel

### ISSUE THREAD

**Issue by yizhou-wang** [ClementPinard/unsupervised-depthnet#1]
There is an error in `prepare_train_data.py` when run in parallel `--num-threads > 1`. Is that caused by a bug? Thank you! 

The error message is like below.
```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/venv-py3/lib/python3.5/site-packages/joblib/externals/loky/process_executor.py", line 420, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/venv-py3/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 563, in __call__
    return self.func(*args, **kwargs)
  File "/home/venv-py3/lib/python3.5/site-packages/joblib/parallel.py", line 261, in __call__
    for func, args, kwargs in self.items]
  File "/home/venv-py3/lib/python3.5/site-packages/joblib/parallel.py", line 261, in <listcomp>
    for func, args, kwargs in self.items]
  File "data/prepare_train_data.py", line 33, in dump_example
    dump_dir = args.dump_root/scene_data['rel_path']
AttributeError: 'Namespace' object has no attribute 'dump_root'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "data/prepare_train_data.py", line 105, in <module>
    main()
  File "data/prepare_train_data.py", line 87, in main
    Parallel(n_jobs=args.num_threads)(delayed(dump_example)(scene) for scene in tqdm(data_loader.scenes))
  File "/home/venv-py3/lib/python3.5/site-packages/joblib/parallel.py", line 996, in __call__
    self.retrieve()
  File "/home/venv-py3/lib/python3.5/site-packages/joblib/parallel.py", line 899, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/venv-py3/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 517, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
AttributeError: 'Namespace' object has no attribute 'dump_root'

```

**Comment by LIANGXINKAI** [comment]
hello,I also get the same problem.
u can settle the problem by correcting prepare_train_data.py;
line 30:  correct "def dump_example(scene):" to  "def dump_example(scene, args):",
line 84:  correct  "dump_example(scene)" to "dump_example(scene, args)"
line 86:  correct  "dump_example(scene)" to "dump_example(scene, args)"

**Comment by ClementPinard** [comment]
Hey, sorry about that, the issue totally went under the radar ! I'll upload a patch very soon
